services:
  newsnow:
    # image: registry.cn-wulanchabu.aliyuncs.com/zhihu2web/newsnow:20250423
    image: glenn/newsnow:20250425
    container_name: newsnow
    restart: always
    ports:
      - '4444:4444'
    environment:
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
